on:
  workflow_dispatch:
  schedule:
  - cron: '5 9 * * 5,6'
jobs:
  Phigros:
    runs-on: ubuntu-20.04
    env:
      SUPER_SECRET: ${{ secrets.PERS }}
    steps:
    - run: |
        git config --global user.name 'GithubAction'
        git config --global user.email 'seed@gmail.com'
        git clone https://$SUPER_SECRET@github.com/7aGiven/PhigrosExtract .
    - run: sh main.sh $SUPER_SECRET
